version: "3.8"

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    network_mode: "host"           # Acceso directo a la red de la VPS
    privileged: true               # Requiere para acceder a puertos bajos como 80/443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      - PUID=0                      # Ejecuta como root
      - PGID=0
      - TZ=Europe/Madrid           # Ajusta tu zona horaria